services:
  apisix:
    image: apache/apisix:3.8.0-debian
    environment:
      - APISIX_STAND_ALONE=true
    volumes:
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    ports:
      - "9080:9080"
      - "9180:9180"
    restart: always
